# Generated by Django 3.2 on 2024-03-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
    ]
